[package]
name = "crypto-object-store"
version = "0.1.0"
edition = "2024"

[dependencies]
url = "2.5.4"
tokio = "1.44.2"
deltalake = {version = "0.25.0", features = ["datafusion"] }
deltalake-core = "0.25.0"
async-trait = "0.1.88"
bytes = "1.10.1"
futures-core = "0.3.31"